### ISSUE TITLE
Use caching to speed up Travis builds

### ISSUE THREAD

**Issue by fabian-rump** [mass-project/mass_api_client#71]
- See https://docs.travis-ci.com/user/caching/#pip-cache
- Check for unintended side effects (i.e. dependency updates still handled correctly?)

**Comment by Silberschleier** [comment]
I tried this on branch feature-71, and the benefits are not that big. Because the api client has only a few small dependencies, the caching saves just around 5 seconds per build.
Even though I don't think side effects will be a problem, I am not sure if it is really worth the 'risk' at the current state.
